name: Deploy to Apache Server

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. install SSH private key
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. deploy
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "\
            cd /var/www/cse135.online/public_html && \
            git pull origin main \
          "
